// tools/src/extract/runner.rs

use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use walkdir::WalkDir;

use swc_common::SourceMap;
use swc_ecma_ast::*;
use swc_ecma_parser::{lexer::Lexer, Parser, StringInput, Syntax};
use swc_ecma_visit::{Visit, VisitWith};

use crate::types::{ExtractedSpec, PropConfig};

/// Consolidated build compilation stage
pub fn build(src_dir: &Path, dist_dir: &Path) {
    let types_dir = dist_dir.join("types");
    sync_src_to_dist(src_dir, dist_dir);
    run(src_dir, &types_dir);
}

pub fn run(src_dir: &Path, dist_types_dir: &Path) {
    let mut specs = Vec::new();

    // 1. Walk through src/elements/ and src/pages/ to parse JS files
    for entry in WalkDir::new(src_dir)
        .into_iter()
        .filter_map(|e| e.ok())
        .filter(|e| e.file_type().is_file())
    {
        let path = entry.path();
        if path.extension().map_or(false, |ext| ext == "js") {
            if let Some(spec) = parse_element_file(path) {
                specs.push((path.to_path_buf(), spec));
            }
        } else if path.extension().map_or(false, |ext| ext == "html") {
            logs::compiler!("Found HTML: {:?}", path);
            if let Err(err) = super::html::parse_and_emit(path) {
                logs::error!("Failed to generate tags descriptor for {:?}: {}", path, err);
            }
        }
    }

    // 2. Write individual .d.ts files and the main index.d.ts
    std::fs::create_dir_all(dist_types_dir).ok();
    
    let mut global_typings = String::new();
    global_typings.push_str("/* Auto-generated by native-tools. Do not edit. */\n\n");
    global_typings.push_str("declare global {\n  interface HTMLElementTagNameMap {\n");

    for (file_path, spec) in &specs {
        let relative_path = file_path.strip_prefix(src_dir).unwrap_or(file_path);
        let mut type_path = dist_types_dir.join(relative_path);
        type_path.set_extension("d.ts");
        if let Some(parent) = type_path.parent() {
            std::fs::create_dir_all(parent).ok();
        }

        // Write the custom element interface declaration
        let dts_content = generate_dts_content(spec);
        std::fs::write(&type_path, dts_content).ok();

        // Add to global HTMLElementTagNameMap augmentation
        let element_class_name = to_pascal_case(&spec.tag);
        logs::compiler!("Extracted element metadata: <{}> -> {}Element", spec.tag, element_class_name);
        
        global_typings.push_str(&format!(
            "    \"{}\": import(\"./{}\").{}Element;\n",
            spec.tag,
            relative_path.to_string_lossy().replace('\\', "/").trim_end_matches(".js"),
            element_class_name
        ));
    }

    global_typings.push_str("  }\n}\n\nexport {};\n");
    std::fs::write(dist_types_dir.join("index.d.ts"), global_typings).ok();
    logs::success!("Type augmentation registry updated inside dist/types/index.d.ts");
}

fn parse_element_file(file_path: &Path) -> Option<ExtractedSpec> {
    let cm: Arc<SourceMap> = Arc::new(SourceMap::default());
    let fm = match cm.load_file(file_path) {
        Ok(f) => f,
        Err(_) => return None,
    };

    let lexer = Lexer::new(
        Syntax::Es(Default::default()),
        Default::default(),
        StringInput::from(&*fm),
        None,
    );

    let mut parser = Parser::new_from(lexer);
    let program = match parser.parse_program() {
        Ok(p) => p,
        Err(_) => return None,
    };

    let mut visitor = ElementVisitor::default();
    program.visit_with(&mut visitor);

    visitor.spec
}

#[derive(Default)]
struct ElementVisitor {
    spec: Option<ExtractedSpec>,
}

impl Visit for ElementVisitor {
    fn visit_call_expr(&mut self, call: &CallExpr) {
        if self.spec.is_some() {
            return;
        }

        // Search for ui.element(...)
        if let Callee::Expr(expr) = &call.callee {
            if let Expr::Member(member) = &**expr {
                if let (Expr::Ident(obj), MemberProp::Ident(prop)) = (&*member.obj, &member.prop) {
                    if obj.sym == "ui" && prop.sym == "element" {
                        if call.args.len() >= 2 {
                            let tag = get_string_literal(&call.args[0].expr);
                            let mut spec = ExtractedSpec {
                                tag: tag.clone().unwrap_or_default(),
                                props: HashMap::new(),
                                methods: Vec::new(),
                            };

                            if let Expr::Object(obj_lit) = &*call.args[1].expr {
                                parse_spec_object(obj_lit, &mut spec);
                            }

                            if !spec.tag.is_empty() {
                                self.spec = Some(spec);
                            }
                        }
                    }
                }
            }
        }

        call.visit_children_with(self);
    }
}

fn get_string_literal(expr: &Expr) -> Option<String> {
    match expr {
        Expr::Lit(Lit::Str(s)) => {
            let str_val = s.value.as_str()?;
            Some(str_val.to_string())
        }
        _ => None,
    }
}

fn parse_spec_object(obj: &ObjectLit, spec: &mut ExtractedSpec) {
    for prop in &obj.props {
        if let PropOrSpread::Prop(p) = prop {
            if let Prop::KeyValue(kv) = &**p {
                if let PropName::Ident(key) = &kv.key {
                    if key.sym == "props" {
                        if let Expr::Object(props_obj) = &*kv.value {
                            parse_props(props_obj, spec);
                        }
                    } else if key.sym == "methods" {
                        if let Expr::Object(methods_obj) = &*kv.value {
                            parse_methods(methods_obj, spec);
                        }
                    }
                }
            }
        }
    }
}

fn parse_props(obj: &ObjectLit, spec: &mut ExtractedSpec) {
    for prop in &obj.props {
        if let PropOrSpread::Prop(p) = prop {
            if let Prop::KeyValue(kv) = &**p {
                if let PropName::Ident(key) = &kv.key {
                    let prop_name = key.sym.to_string();
                    let mut config = PropConfig::default();

                    if let Expr::Object(config_obj) = &*kv.value {
                        for c_prop in &config_obj.props {
                            if let PropOrSpread::Prop(cp) = c_prop {
                                if let Prop::KeyValue(ckv) = &**cp {
                                    if let PropName::Ident(ckey) = &ckv.key {
                                        if ckey.sym == "type" {
                                            if let Expr::Ident(type_ident) = &*ckv.value {
                                                config.prop_type = type_ident.sym.to_string();
                                            }
                                        } else if ckey.sym == "reflect" {
                                            if let Expr::Lit(Lit::Bool(b)) = &*ckv.value {
                                                config.reflect = b.value;
                                            }
                                        } else if ckey.sym == "state" {
                                            if let Expr::Lit(Lit::Bool(b)) = &*ckv.value {
                                                config.state = b.value;
                                            }
                                        } else if ckey.sym == "default" {
                                            config.default = Some("any".to_string());
                                        }
                                    }
                                }
                            }
                        }
                    }

                    spec.props.insert(prop_name, config);
                }
            }
        }
    }
}

fn parse_methods(obj: &ObjectLit, spec: &mut ExtractedSpec) {
    for prop in &obj.props {
        if let PropOrSpread::Prop(p) = prop {
            match &**p {
                Prop::KeyValue(kv) => {
                    if let PropName::Ident(key) = &kv.key {
                        spec.methods.push(key.sym.to_string());
                    }
                }
                Prop::Method(m) => {
                    if let PropName::Ident(key) = &m.key {
                        spec.methods.push(key.sym.to_string());
                    }
                }
                _ => {}
            }
        }
    }
}

fn generate_dts_content(spec: &ExtractedSpec) -> String {
    let mut content = String::new();
    let class_name = to_pascal_case(&spec.tag);

    content.push_str(&format!(
        "/* Auto-generated definition for <{}>. Do not edit. */\n\n",
        spec.tag
    ));
    content.push_str(&format!(
        "export interface {}Element extends HTMLElement {{\n",
        class_name
    ));

    // Properties typing mapping
    for (name, config) in &spec.props {
        let ts_type = match config.prop_type.as_str() {
            "Boolean" => "boolean",
            "Number" => "number",
            "String" => "string",
            _ => "any",
        };
        content.push_str(&format!("  {}: {};\n", name, ts_type));
    }

    // Methods typing mapping
    for method in &spec.methods {
        content.push_str(&format!("  {}(...args: any[]): any;\n", method));
    }

    content.push_str("}\n");
    content
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut capitalize = true;
    for c in s.chars() {
        if c == '-' {
            capitalize = true;
        } else if capitalize {
            result.push(c.to_ascii_uppercase());
            capitalize = false;
        } else {
            result.push(c);
        }
    }
    // Remove "Ui" prefix from start if it starts with "Ui"
    if result.starts_with("Ui") {
        result.split_off(2)
    } else {
        result
    }
}

/// Simple directory copy to mirror src to dist (build mode only)
fn sync_src_to_dist(src: &Path, dist: &Path) {
    std::fs::create_dir_all(dist).ok();
    for entry in walkdir::WalkDir::new(src)
        .into_iter()
        .filter_map(|e| e.ok())
    {
        let path = entry.path();
        let relative = path.strip_prefix(src).unwrap_or(path);
        let target = dist.join(relative);

        if path.is_dir() {
            std::fs::create_dir_all(&target).ok();
        } else {
            if let Some(parent) = target.parent() {
                std::fs::create_dir_all(parent).ok();
            }
            std::fs::copy(path, &target).ok();
        }
    }
}
